### ISSUE TITLE
Develop initial user interface

### ISSUE THREAD

**Issue by andrew-fennell** [andrew-fennell/CogNative#42]
Create initial user interface.

File browser:
- Source audio file path
- Destination audio file path

Dropdown:
- Source language (checkbox to auto detect language)
- Destination language

Button:
- Run vocal synthesis
- Play audio

Some decisions need to be made about technologies. Those decision can be added here as comments.

**Comment by austin-currington** [comment]
Writing here to note down the (very very optional) idea that we could try adding our process to the context menu so users can right click on a downloaded media file and get the output version after checking a few boxes and/or entering filenames and language selections and such in a convenient way.

**Comment by Aref-Sadeghi-Gh** [comment]
I just created a simple UI using python tkinter to upload files. We can customize the winodw and button and stuff in Tkinter. Unless we want to implement the front-end using a different platform, I think tkinter should do the job.

**Comment by andrew-fennell** [comment]
@Aref-Sadeghi-Gh I think tkinter is fine since it works well with our Python backend. We can always adjust in the future, but tkinter should be simple.
